### PR TITLE
Add paging options.

### PR DESCRIPTION
**Pull request by MrMaksimize**

### CODE REVIEW

**Comment by dmpe** [comment]
hi. thanks for the PR. But wouldnt it be better to set default to 100 ?

**Comment by dmpe** [comment]
actually not. i will merge an then: release to cran i see however much later ..cca. end of may unless you give me a very good reason to send it to them earlier

**Comment by MrMaksimize** [comment]
I default to 25 because the wufoo api defaults to 25 if the parameter is not passed :) http://help.wufoo.com/articles/en_US/SurveyMonkeyArticleType/The-Entries-GET-API

I don't know how CRAN uploading works.  Is it a big pain to do update packages?

**Comment by dmpe** [comment]
ok. you convinced me to upload it to cran soon. is it the only PR you are 
going to contribute ? or should i wait for some more ? 

# again thank you ver much !

**Comment by MrMaksimize** [comment]
Haha cool!  I'm glad I could convince you.  I needed it pretty fast -- as soon as I had over 25 entries.  

I have it doing what I need to now (https://github.com/cityofsandiego/datasd/blob/reporting/tools/inventoryReporter.R#L32-L42 - in case you're curious) so don't foresee any more PRs :)  

And thank _you_ for making this project -- this is extremely useful!

**Comment by dmpe** [comment]
will upload today

**Pull request merged**
